### ISSUE TITLE
Global Filter Related Crash

### ISSUE THREAD

**Issue by hiddenindians** [unexpectedpanda/retool#128]
**Describe the bug**
Custom global filter /.*\(Beta\s?[0-9]?\) causes the application to crash. The CLI outputs this at crash time:

```
Traceback (most recent call last): for includes... [4%]
  File "/home/user/retool-main/retool-gui.py", line 1020, in <module>
    main()
  File "/home/user/retool-main/retool-gui.py", line 622, in main
    retool.main(gui_input)
  File "/home/user/retool-main/retool.py", line 314, in main
    recovered_groups = recover_titles_for_custom_filters(user_input, input_dat, dat_numbered, recovered_groups, region_data, REGEX)
  File "/home/user/retool-main/modules/customfilters.py", line 156, in recover_titles_for_custom_filters
    DatNode(node, region, region_data, user_input, input_dat, dat_numbered, REGEX))
  File "/home/user/retool-main/modules/classes.py", line 70, in __init__
    self.implied_language = region_data.implied_language[region]
KeyError: 'Japan, USA'
```

**To reproduce**
Select your dat file and output folder.
Leave regions, languages, exclusions, modes, and custom system filters with default settings. Under Custom global filters enter /[/s/S] in the Exclude list. Enter /.*\(Beta\s?[0-9]?\) in the Include list. Click "Go!"

**Expected behavior**
The application should output a DAT file showing only titles that have (Beta) or (Beta #) - where # represents a single digit number - in their name. 

**Operating system**

- [ ] Ubuntu

**Retool edition**

- [ 0.99] retool.py
- [ 0.11] retool-gui.py

**Retool version**
For the command line edition of Retool, the version is shown when you run it with no other arguments.

For the GUI edition, click **Help**, then **About**.

**Are you using custom global or system filters? If so, list them below**

Global excludes: /[/s/S] 

Global includes: /.*\(Beta\s?[0-9]?\)

System excludes:

System includes:

**What other settings are you using?**
Everything else is default.
**Additional context**
This might have something to do with the word 'Beta'? If you swap it out for 'Proto' there's no issue. The app runs fine and the output is accurate.

**Comment by hiddenindians** [comment]
I was using the Atari - 2600 (20211007-214713).dat from no-intro
[Atari - 2600 (20211007-214713).zip](https://github.com/unexpectedpanda/retool/files/7318234/Atari.-.2600.20211007-214713.zip)
.
