### ISSUE TITLE
Win8 Retool doesn't launches (both GUI/CLI)

### ISSUE THREAD

**Issue by Xeretinha** [unexpectedpanda/retool#223]
As said on title, fresh install of Retool -both GUI than CLI versions) isn't launching on Windows 8 (not the 8.1).
The console results on the following:
(GUI Version)
```
Traceback (most recent call last):
  File "retool-gui.py", line 53, in <module>
  File "ctypes\__init__.py", line 387, in __getattr__
  File "ctypes\__init__.py", line 392, in __getitem__
AttributeError: function 'SetProcessDpiAwareness' not found
[1620] Failed to execute script 'retool-gui' due to unhandled exception!
```
(CLI version)
```
Traceback (most recent call last):
  File "retool-gui.py", line 53, in <module>
    ctypes.windll.shcore.SetProcessDpiAwareness(0)
  File "C:\Program Files\Python38\lib\ctypes\__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "C:\Program Files\Python38\lib\ctypes\__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'SetProcessDpiAwareness' not found
```
Currently using Python 3.8.10, and the required packages said at CLI guide has been already installed. Plus, path is right setted on system variables.

NOTE: Before creating this issue, i'v checked the open/closed ones and saw other two ([one open](https://github.com/unexpectedpanda/retool/issues/170) and [one already closed](https://github.com/unexpectedpanda/retool/issues/9)) about misconfiguration on 4k monitors, so - since there are something DPI related on the error messages - would be good to say that i'm using a dual config display where the main screen is a FullHD TV (1920x1080p) while secondary is a laptop monitor (1366x768p).

**Comment by unexpectedpanda** [comment]
Hi there! It looks like Windows 8 can't find the [`SetProcessDpiAwareness`](https://learn.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process) function, which is likely because it first became available in Windows 8.1.

In theory this is a small fix, but I don't have a copy of Windows 8 to test against, only 8.1. I should also point out that Retool isn't supported on Windows versions prior to 10. That's not really made clear anywhere though other than when you create an issue, so that one is on me to fix.

I'll push out a small change in the coming days, but you'll need to verify for me things are working. 

One more thing: I'm not sure why your CLI sample quotes `retool-gui.py`. If you're running the CLI version, you should just be running `retool.py`, which doesn't interact with the GUI version.

**Comment by unexpectedpanda** [comment]
Okay, redownload Retool and see if that addresses your issue.

**Comment by Xeretinha** [comment]
> Hi there! It looks like Windows 8 can't find the [`SetProcessDpiAwareness`](https://learn.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process) function, which is likely because it first became available in Windows 8.1.
> 
> In theory this is a small fix, but I don't have a copy of Windows 8 to test against, only 8.1. I should also point out that Retool isn't supported on Windows versions prior to 10. That's not really made clear anywhere though other than when you create an issue, so that one is on me to fix.
> 
> I'll push out a small change in the coming days, but you'll need to verify for me things are working.

I'v downloaded retool-gui.py isolately and replaced it on the CLI version directory, then "pythoned it" through console: it ran and the GUI opened normally! So I guess you'd hit the spot!
Issue may has been solved!

> One more thing: I'm not sure why your CLI sample quotes `retool-gui.py`. If you're running the CLI version, you should just be running `retool.py`, which doesn't interact with the GUI version.

I guess may has my bad here: I'v downloaded both GUI than CLI versions, and then executed the Linux-oriented GUI version that comes with the steps for CLI version. See: I'm not that familiarized with Python and even with pure command line for ROM managing (remembering the whole list of regions PLUS languages to make a full 1G1R pack w/o ignoring even a last game, but priorizing those ones more "language-friendly" - a.k.a.: that uses ocidental alphabetics? By hobby? Madness, huh?!?), so I may had mistaken a bit following the Linux GUI version steps realizing that was just an alternative to not compiled binary CLI version...

Good news is that the issue would make ReTool (even binary ones) backyard compatible to older Win versions with a plus about compatibility of Linux-to-Win version also...
Bad side is that I may be too disctracted lately to make soo rudimentar mistakes! ~_~'


PS: I'll let for you to close the issue, since you are awaiting confirmation and still will commit the changes on the binary files.

**Comment by unexpectedpanda** [comment]
Good to hear it's fixed :)

The binary for Windows users has also been silently updated.
