### ISSUE TITLE
Clone List Error

### ISSUE THREAD

**Issue by FidoFuz** [unexpectedpanda/retool#250]
**Describe the bug**
After fetching the updated clone list the Sega Mega Drive - Genesis NoIntro dat produces an error:

* Applying clone list overrides... done.
* Analyzing clone list variants... done.
* Applying category and user excludes... done.
* Removing titles without specified languages... done.
* Removing titles without specified regions... done.
* Selecting 1G1R titles [###############!    ] (!) 3/4 [75%] in 3.0s

* Unexpected error:

Traceback (most recent call last):
  File "d:\Retool2\retool.py", line 293, in <module>
    main()
  File "d:\Retool2\retool.py", line 208, in main
    processed_titles = ParentTools.choose_parent(processed_titles, config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Retool2\modules\chooseparent.py", line 1513, in choose_parent
    processed_titles = ParentTools.choose_compilations(compilations, processed_titles, config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Retool2\modules\chooseparent.py", line 313, in choose_compilations
    ideal_combination: tuple[tuple[str, ...], ...] = tuple(sorted([sorted(x, key=lambda y: (len, y)) for x in stage_2_candidates])[0])
                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range


Press any key to quit Retool

**To reproduce**
python retool.py "Sega - Mega Drive - Genesis (20230410-115930).dat" -l --output c:\dattemp --exclude aAbBcdDemMopPruv

**Operating system**
- [x] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [ ] retool-gui.exe
- [x] retool.py
- [x] retool-gui.py

**Retool version**
2.00.0 Beta 7

**Comment by FidoFuz** [comment]
Update to Beta 9 resolves
