### ISSUE TITLE
Error with version retool-2.02.1

### ISSUE THREAD

**Issue by maxexcloo** [unexpectedpanda/retool#302]
**Describe the bug**

**To reproduce**
Run retool.py with python.

**Expected behavior**
```
max.schaefer@mini:/Volumes/Data/media/games/test$ cd retool-2.02.0/
max.schaefer@mini:/Volumes/Data/media/games/test/retool-2.02.0$ python3 retool.py 


Retool 2.02.0
-------------
Filters DATs from Redump (http://redump.org/) and No-Intro
(https://www.no-intro.org/) to remove titles you don't want. A new DAT
file is automatically generated, the original file isn't altered.

Usage: retool.py <input DAT/folder> <options>

OR to download updated clone lists:

retool.py --update

Type retool.py -h for all options
```

**Operating system**
macOS

**Retool edition**
retool.py

**Retool version**
retool-2.02.1

**Additional context**
```
max.schaefer@mini:/Volumes/Data/media/games/test$ cd retool-2.02.1/
max.schaefer@mini:/Volumes/Data/media/games/test/retool-2.02.1$ python3 retool.py 
Traceback (most recent call last):
  File "/Volumes/Data/media/games/test/retool-2.02.1/retool.py", line 35, in <module>
    from modules.output import WriteFiles
  File "/Volumes/Data/media/games/test/retool-2.02.1/modules/output.py", line 327
    f'\t\t<{rom['type']} {" ".join(rom_xml)}/>\n')
                 ^^^^
SyntaxError: f-string: unmatched '['
```

**Comment by unexpectedpanda** [comment]
Weirdly this works perfectly fine on Windows... which it shouldn't.

I hope you're willing to test something for me, as I'm not running macOS.

Open `modules/output.py`, and go to line 327.

Replace:

```
f'\t\t<{rom['type']} {" ".join(rom_xml)}/>\n')
```

With:

```
f'\t\t<{rom["type"]} {" ".join(rom_xml)}/>\n')
```

If you have no further problems, I'll push out a new version with that change to fix the issue.

**Comment by maxexcloo** [comment]
Yup that fixed it!

**Comment by unexpectedpanda** [comment]
Thanks for your help :) I've updated the `modules/output.py` file in the repo. No need for a version increment on this one I think.
