### ISSUE TITLE
Prefer modern rereleases Option does not work

### ISSUE THREAD

**Issue by FakeSpam** [unexpectedpanda/retool#329]
The option for "Prefer titles ripped from modern rereleases over original system releases" will cause an error and fail. To reproduce this issue, check the option in the options tab. This issue appears in both Ubuntu 22.04 and Windows 10 using retool-gui. This issue does not appear if the option is not selected.
Apologies for the following big block of text, I don't know how to format.

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "multiprocessing\pool.py", line 125, in worker
  File "multiprocessing\pool.py", line 48, in mapstar
  File "modules\chooseparent.py", line 3202, in choose_parent_process
UnboundLocalError: cannot access local variable 'modern_edition_regex_tags' where it is not associated with a value
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "retoolgui.py", line 279, in run
  File "retool.py", line 245, in main
  File "modules\chooseparent.py", line 2404, in choose_parent
  File "multiprocessing\pool.py", line 367, in map
  File "multiprocessing\pool.py", line 774, in get
UnboundLocalError: cannot access local variable 'modern_edition_regex_tags' where it is not associated with a value

**Comment by unexpectedpanda** [comment]
Thanks, the fix will be in the next release.
