### ISSUE TITLE
Character encoding problem

### ISSUE THREAD

**Issue by Freeben666** [unexpectedpanda/retool#89]
**Describe the bug**
Retool is having trouble handling some DATs, regarding character encoding apparently

**To reproduce**
Run retool on the attached DATs
[DATs.zip](https://github.com/unexpectedpanda/retool/files/6565315/DATs.zip)

**Expected behavior**
Should filter the DATs without trouble

**Operating system**
- [X ] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [X ] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
Retool GUI: 0.10
Retool CLI: 0.91

**Are you using custom global or system filters? If so, list them below**

Global excludes: None

Global includes: None

System excludes: None

System includes: None

**What other settings are you using?**
Regions: France > Europe > World > Unknown
Languages: English + French

**Additional context**
* Reading dat file: "D:\Emulation\Tools\Retool\DATs\IBM - PC and Compatibles
  (Digital) (Steam) (Extracted) (20200327-110556).dat"
* Validating dat file... Traceback (most recent call last):
  File "retool-gui.py", line 1004, in <module>
  File "retool-gui.py", line 611, in main
  File "retool.py", line 142, in main
  File "modules\xml.py", line 488, in process_input_dat
  File "c:\users\lister\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 5547: character maps to <undefined>
[19432] Failed to execute script retool-gui

* Reading dat file: "D:\Emulation\Tools\Retool\DATs\IBM - PC and Compatibles
  (Digital) (Misc) (20210526-132648).dat"
* Validating dat file... Traceback (most recent call last):
  File "retool-gui.py", line 1004, in <module>
  File "retool-gui.py", line 611, in main
  File "retool.py", line 142, in main
  File "modules\xml.py", line 488, in process_input_dat
  File "c:\users\lister\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 8027: character maps to <undefined>
[1556] Failed to execute script retool-gui

**Comment by unexpectedpanda** [comment]
Amazingly, I've already fixed this in 0.92 for a different dat. It's been a little held up, but hopefully won't be too long.

**Comment by Freeben666** [comment]
Nice ! I'll just be patient and wait for v0.92 release. Thanks !

**Comment by unexpectedpanda** [comment]
Released!
