### ISSUE TITLE
Latest retool crashing at startup

### ISSUE THREAD

**Issue by Gazpr0m** [unexpectedpanda/retool#94]
Downloaded latest binary for windows(0.93) and when I click on the retool-gui.exe it immediately closes.
Starting from a prompt I get this:

PS D:\temp\retool> .\retool-gui.exe
PySide2/__init__.py: Unable to import shiboken2 from D:\temp\retool\base_library.zip, D:\temp\retool\lib-dynload, D:\temp\retool
Traceback (most recent call last):
  File "retool-gui.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "PySimpleGUIQt\__init__.py", line 2, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "PySimpleGUIQt\PySimpleGUIQt.py", line 25, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "PySide2\__init__.py", line 107, in <module>
  File "PySide2\__init__.py", line 58, in _setupQtDirectories
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "shiboken2\__init__.py", line 27, in <module>
ModuleNotFoundError: No module named 'shiboken2.shiboken2'
[11820] Failed to execute script retool-gui
PS D:\temp\retool>

Earlier versions worked great. Win10 21H1

**Comment by Gazpr0m** [comment]
Eh, 7-zip for some reason doesn't extract that file when using Extract files instead of Extract to ''
Closing..

**Comment by unexpectedpanda** [comment]
When using **Extract files** in 7-Zip, make sure **Path mode** is set to **Full pathnames**. That should keep everything intact in the required folders.
